### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by maximecb** [lcswillems/pytorch-a2c-ppo#10]
Could you please add an open source license to this repo? Usually this is in a file named `LICENSE`. I would recommend something very liberal like the [MIT one](https://en.wikipedia.org/wiki/MIT_License). You can put your own name as the copyright holder. It's just that without this, your code can't legally be assumed to be open source, AFAIK.

**Comment by lcswillems** [comment]
I have just added a MIT license as you suggest.
