### ISSUE TITLE
Tensorboard not working

### ISSUE THREAD

**Issue by fabian57fabian** [lcswillems/pytorch-a2c-ppo#12]
I've installed all the packages in miniconda called "pytorch" and run all. It all worked until trying tensorboard:

I installed tensorboard with:
`pip3 install tensorboardX`
And then added --tb at the end of training line code but got a segmentation fault:
`(pytorch) fabian_57@Gregor:~/python_libraries/pytorch-a2c-ppo$ python3 -m train --algo ppo --env MiniGrid-DoorKey-6x6-v0 --no-instr --no-mem --model DoorKey-6x6-ppo --save-interval 10 --tb
Segmentation fault (core dumped)
`
Also when trying to view some results i got:
`(pytorch) fabian_57@Gregor:~/python_libraries/pytorch-a2c-ppo$ tensorboard --logdir storage
tensorboard: command not found
`
Even if with pip3 list i got tensorboardX as installed!

Do i really have to install tensorflow and then tensorboardX to make it work?

**Comment by lcswillems** [comment]
Hi,

Honestly, I have no idea why you have this error...
When you find the solution, let me know and I will update the code accordingly.

Thank you for this issue,
Lucas

**Comment by fabian57fabian** [comment]
I solved the problem!
TensorboardX uses tensorboard that requires tensorflow.
I currently have python 3.7 witch is not supported by tensorflow.
I created a new environment, installed python 3.6, installed tensorflow, tensorboard, tensorboardX and all needed packages and now it works.
Maybe you could insert a note in Read.me near tensorboardX info and say that it works only on python 3.6.

Cheers,
Fabian Greavu

**Comment by lcswillems** [comment]
Thank you for the solution!
And @maximecb , this is already the case!
