### ISSUE TITLE
Issue with relative imports

### ISSUE THREAD

**Issue by maximecb** [lcswillems/pytorch-a2c-ppo#9]
I'm trying to setup automated testing with CircleCI and running into issues with the absolute imports used by this package, eg:

https://github.com/lcswillems/pytorch-a2c-ppo/blob/master/torch_rl/torch_rl/__init__.py#L1
https://github.com/lcswillems/pytorch-a2c-ppo/blob/master/torch_rl/torch_rl/algos/base.py#L5

Example error: https://circleci.com/gh/maximecb/baby-ai-game/4

```
 File "/home/circleci/project/babyai/utils/format.py", line 6, in <module>
    import torch_rl
  File "/home/circleci/.local/lib/python3.5/site-packages/torch_rl/__init__.py", line 1, in <module>
    from torch_rl.algos import A2CAlgo, PPOAlgo
ImportError: No module named 'torch_rl.algos'
```

So, as you can see `torch_rl` imports, but `torch_rl.algos` doesn't resolve within the `torch_rl` package. I would suggest either switching to relative imports, eg: `from .algos import A2CAlgo, PPOAlgo`, or modifying `setup.py` to export the subpackages as well.

You can take a look at how the baby-ai-game package exports subpackage names: https://github.com/maximecb/baby-ai-game/blob/master/setup.py#L8

**Comment by lcswillems** [comment]
I updated the `setup.py`, it should be working now.

**Comment by maximecb** [comment]
Working :+1:
